# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HOk1by0SlwEVVMPGECfYevhHZdfWQ0YS
"""

first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
full_name = first_name + " " + last_name

alternate_chars = full_name[::2]

print("Full Name:", full_name)
print("Alternate Characters:", alternate_chars)

text = open("input.txt", "r")
d = dict()
for line in text:
  line = line.strip()
  line = line.lower()
  words = line.split(" ")
  for word in words:

        if word in d:

            d[word] = d[word] + 1
        else:

            d[word] = 1


for key in list(d.keys()):
    print(key, ":", d[key])

lst1 = []
n = int(input("enter number of customers: "))
for i in range(n) :
  height = int(input ("Enter the height of customers in inches: "))
  lst1.append(height)
lst1 = [height * 2.54 for height in lst1]
print(lst1)